### ISSUE TITLE
Nytt endepunkt med bedre semantikk

### ISSUE THREAD

**Issue by rannveigskjerve** [navikt/tms-mikrofrontend-selector#40]
forslag til path: `/content`

- [ ] sette opp ny rute
- [ ] endre feltet "microfrontends" til "dinOversikt"

**Comment by Amirhlotfi** [comment]
endepunktet /microfrontends endret til /din-oversikt

https://github.com/navikt/tms-mikrofrontend-selector/pull/47
https://github.com/navikt/tms-mikrofrontend-selector/pull/48
